# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximo Divisor Comum
#'
#' @param x Um número (int)
#' @param y Um número (int)
#' @return O MDC entre `x` e `y`
#' @useDynLib pacote2, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
mdc_rcpp <- function(x, y) {
    .Call(`_pacote2_mdc_rcpp`, x, y)
}

drayleigh <- function(x, sigma) {
    .Call(`_pacote2_drayleigh`, x, sigma)
}

